### ISSUE TITLE
Does Dihedral analysis  use dimensions from separate universes?

### ISSUE THREAD

**Issue by orbeckst** [Becksteinlab/MDPOW#215]
It looks as if DihedralAnalysis takes a short cut and only uses the dimensions of the first ensemble member:
https://github.com/Becksteinlab/MDPOW/blob/2092cfd3f1cb006b38d01ec722dd2040f221a5c4/mdpow/analysis/dihedral.py#L102-L103

This can lead to **wrong results**. Instead, the calculations need to be done for each universe separately.

**Comment by orbeckst** [comment]
@ALescoulie can you please explain what's happening in DihedralAnalysis — did I misunderstand how it works?

**Comment by ALescoulie** [comment]
@orbeckst In `_single_frame` it's looking at stuff from a single universe, I just split in into 4 `EnsembleAtomGroup`s. At the beginning `_reorg_groups` takes the given dihedral selections and makes 4 `EnsembleAtomGroup`s each just containing the one atoms of each dihedral in the inputted dihedrals. This done for efficiency (I think I found that it was slower in my report) since we could do the dihedral calculations together with only one call to Cython. One of the functions called in `__init__` ensures the passed in list is all from the same `Ensemble`. I don't think this is an issue.

**Comment by orbeckst** [comment]
Thank you for the explanation. I didn't understand how the current universe is selected. This all makes more sense now.

(Incidentally, you had actually fixed the box in #198 ).
