### ISSUE TITLE
TIP4P-D water model

### ISSUE THREAD

**Issue by orbeckst** [Becksteinlab/MDPOW#81]
J Phys Chem B. 2015 Apr 23;119(16):5113-23. doi: 10.1021/jp508971m. Epub 2015 Apr 13.
Water dispersion interactions strongly influence simulated structural properties of disordered protein states. https://www.ncbi.nlm.nih.gov/pubmed/25764013

Just heard BPS talk by Robustelli from DESRES on good progress by using new water model to describe both folded **and** unfolded state. We should try it for MDPOW.

Opinions @iorga ?

**Comment by iorga** [comment]
I think that it's worth to try. I will try to create a .itp file for the new water model.

**Comment by orbeckst** [comment]
Great, thanks. The talks in the session all go on about water models... will give us a way to also contribute to the discussion from the point of view of solvation free energies.

**Comment by iorga** [comment]
I have created a tentative TIP4P-D water model (called _tip4pd_), see the last commit e5cdb4c98387a459090567c36af200519fb14285 into a new branch. @orbeckst , please have a look in _mdpow/top/oplsaa.ff_ especially at the files _tip4pd.itp_ and _ffnonbonded.itp_ (at the end).

I have also identified and fixed an error in the M24 water model (the heavy mass was used for OW instead of the normal one). We will need to do again all the simulations with this water model.

**Comment by iorga** [comment]
TIP4P-D water model was implemented in #141.

**Comment by orbeckst** [comment]
4-year old issue closed! yay!
